# -*- coding: utf-8 -*-
"""AI_Career_Advisor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEXXDl9yWbLJfvszRRDdwv-mF1WjfaIA

**Install Dependencies**
"""

# !pip install -q langgraph pydantic PyMuPDF groq

import langgraph
from backend.database import supabase

from langgraph.graph import StateGraph, START, END

"""**API Key Setup**"""

import os
from getpass import getpass

if not os.environ.get("GROQ_API_KEY"):
    os.environ["GROQ_API_KEY"] = getpass("Enter your Groq API key: ")

GROQ_MODEL = "openai/gpt-oss-20b"
LLM_TEMPERATURE = 0.3
LLM_MAX_RETRIES = 2

"""

**Pydantic models for every structured output**
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Resume information extraction
# ---------------------------------------------------------------------------

class EducationEntry(BaseModel):
    institution: str = Field(description="Name of the school/university.")
    degree: str = Field(description="Degree or program name, e.g. 'B.Tech Computer Science'.")
    start_year: str | None = Field(default=None, description="Start year, if stated.")
    end_year: str | None = Field(default=None, description="End year or 'Present'.")
    grade: str | None = Field(default=None, description="GPA/percentage/grade if mentioned.")


class ExperienceEntry(BaseModel):
    company: str = Field(description="Employer/organization name.")
    role: str = Field(description="Job title / role held.")
    start_date: str | None = Field(default=None)
    end_date: str | None = Field(default=None, description="'Present' if ongoing.")
    responsibilities: list[str] = Field(
        default_factory=list, description="Key responsibilities or achievements."
    )


class ProjectEntry(BaseModel):
    title: str
    description: str
    technologies: list[str] = Field(default_factory=list)


class CertificationEntry(BaseModel):
    name: str
    issuer: str | None = None
    year: str | None = None


class ResumeExtraction(BaseModel):
    """Structured breakdown of a raw resume text."""

    education: list[EducationEntry] = Field(default_factory=list)
    experience: list[ExperienceEntry] = Field(default_factory=list)
    projects: list[ProjectEntry] = Field(default_factory=list)
    certifications: list[CertificationEntry] = Field(default_factory=list)
    candidate_name: str | None = Field(default=None, description="Full name of the candidate, if found.")
    total_experience_years: float | None = Field(
        default=None, description="Estimated total years of professional experience."
    )


# ---------------------------------------------------------------------------
# Career goal understanding
# ---------------------------------------------------------------------------

class CareerGoal(BaseModel):
    desired_role: str = Field(description="The specific job title the candidate is targeting.")
    desired_industry: str = Field(description="Industry or sector of interest.")
    career_interests: list[str] = Field(
        default_factory=list, description="Broader interests/domains the candidate cares about."
    )
    seniority_level: Literal["entry", "mid", "senior", "lead", "executive"] = Field(
        default="entry", description="Best-guess seniority level implied by the goal/experience."
    )


# ---------------------------------------------------------------------------
# Skill extraction
# ---------------------------------------------------------------------------

class SkillExtraction(BaseModel):
    technical_skills: list[str] = Field(default_factory=list)
    soft_skills: list[str] = Field(default_factory=list)
    tools_and_platforms: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Required skills for target role
# ---------------------------------------------------------------------------

class RequiredSkills(BaseModel):
    role: str
    industry: str
    must_have_skills: list[str] = Field(default_factory=list)
    good_to_have_skills: list[str] = Field(default_factory=list)
    typical_tools: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Skill gap analysis
# ---------------------------------------------------------------------------

class SkillGapAnalysis(BaseModel):
    matched_skills: list[str] = Field(default_factory=list)
    missing_skills: list[str] = Field(default_factory=list)
    partially_matched_skills: list[str] = Field(
        default_factory=list, description="Skills the candidate has at a basic level but the role needs deeper expertise."
    )
    skill_match_percentage: float = Field(
        ge=0.0, le=100.0, description="Percentage of required skills already matched."
    )


# ---------------------------------------------------------------------------
# Learning roadmap
# ---------------------------------------------------------------------------

class WeeklyGoal(BaseModel):
    week_number: int
    focus_area: str
    goals: list[str] = Field(default_factory=list)


class RoadmapPhase(BaseModel):
    duration_days: Literal[30, 60, 90]
    milestones: list[str] = Field(default_factory=list)
    weekly_goals: list[WeeklyGoal] = Field(default_factory=list)


class LearningRoadmap(BaseModel):
    thirty_day: RoadmapPhase
    sixty_day: RoadmapPhase
    ninety_day: RoadmapPhase


# ---------------------------------------------------------------------------
# Course recommendations
# ---------------------------------------------------------------------------

class CourseRecommendation(BaseModel):
    title: str
    provider: str
    url: str | None = Field(default=None, description="Best-guess canonical URL if confidently known.")
    skill_covered: str
    cost_type: Literal["free", "paid"]


class CourseRecommendationSet(BaseModel):
    free_courses: list[CourseRecommendation] = Field(default_factory=list)
    paid_courses: list[CourseRecommendation] = Field(default_factory=list)
    certifications: list[CourseRecommendation] = Field(default_factory=list)
    books: list[str] = Field(default_factory=list)
    youtube_resources: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Project recommendations
# ---------------------------------------------------------------------------

class RecommendedProject(BaseModel):
    title: str
    difficulty: Literal["beginner", "intermediate", "advanced"]
    description: str
    skills_learned: list[str] = Field(default_factory=list)
    estimated_time: str = Field(description="Human-readable estimate, e.g. '2 weeks'.")


class ProjectRecommendationSet(BaseModel):
    projects: list[RecommendedProject] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Resume review / ATS
# ---------------------------------------------------------------------------

class ResumeReview(BaseModel):
    ats_score: float = Field(ge=0.0, le=100.0, description="Estimated ATS compatibility score.")
    weak_sections: list[str] = Field(default_factory=list)
    suggested_improvements: list[str] = Field(default_factory=list)
    missing_keywords: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Interview questions
# ---------------------------------------------------------------------------

class InterviewQuestionSet(BaseModel):
    hr_questions: list[str] = Field(default_factory=list)
    technical_questions: list[str] = Field(default_factory=list)
    behavioral_questions: list[str] = Field(default_factory=list)
    role_specific_questions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Career summary
# ---------------------------------------------------------------------------

class CareerSummary(BaseModel):
    headline: str = Field(description="One-line summary of the candidate's career positioning.")
    overview: str = Field(description="A few paragraphs summarizing the full analysis.")
    strengths: list[str] = Field(default_factory=list)
    priority_actions: list[str] = Field(
        default_factory=list, description="Top 3-5 next actions the candidate should take."
    )
    confidence_score: float = Field(
        ge=0.0, le=100.0, description="Model's confidence in the overall analysis quality."
    )

"""**Prompts**"""

# ---------------------------------------------------------------------------
# Resume information extraction
# ---------------------------------------------------------------------------

RESUME_EXTRACTION_SYSTEM_PROMPT = """\
You are an expert resume parser used inside a career-advisory platform.

Given the raw text of a candidate's resume, extract a structured, factual
breakdown of their background. Rules:
- Only extract information that is explicitly present in the text. Never invent
  companies, dates, degrees, or projects.
- Normalize dates where possible (e.g. "Jan 2022" stays as written if unclear).
- If a section is entirely absent from the resume, return an empty list for it.
- Do not editorialize or add commentary; extraction should be purely factual.
"""


def build_resume_extraction_user_prompt(resume_text: str) -> str:
    return f"Resume text:\n---\n{resume_text}\n---\n\nExtract the structured information."


# ---------------------------------------------------------------------------
# Career goal understanding
# ---------------------------------------------------------------------------

CAREER_GOAL_SYSTEM_PROMPT = """\
You are a career-advisory assistant. Given a candidate's stated career goal
(in their own words) and, optionally, context from their resume, determine:
- The specific desired job role/title (be concrete; if vague, infer the most
  reasonable specific role, e.g. "something in tech" -> "Software Engineer").
- The desired industry.
- Broader career interests.
- A best-guess seniority level based on stated goal and experience.
If the candidate's input is ambiguous, make the most reasonable professional
assumption rather than leaving fields empty.
"""


def build_career_goal_user_prompt(
    stated_goal: str, resume_summary_context: str
) -> str:
    return (
        f"Candidate's stated career goal:\n{stated_goal}\n\n"
        f"Relevant resume context:\n{resume_summary_context}\n\n"
        "Determine the structured career goal."
    )


# ---------------------------------------------------------------------------
# Skill extraction
# ---------------------------------------------------------------------------

SKILL_EXTRACTION_SYSTEM_PROMPT = """\
You are a technical recruiter analyzing a candidate's background. Extract every
skill demonstrated by their resume content (experience, projects, certifications,
and any explicit skills section), and classify each into:
- technical_skills: programming languages, frameworks, methodologies, domain
  knowledge (e.g. "Python", "Machine Learning", "Financial Modeling").
- soft_skills: interpersonal/behavioral skills evidenced by their experience
  (e.g. "Leadership", "Cross-functional Communication").
- tools_and_platforms: concrete named tools/software/platforms (e.g. "AWS",
  "Figma", "Jira", "PostgreSQL").
Deduplicate and use consistent, industry-standard naming for each skill.
"""


def build_skill_extraction_user_prompt(resume_context: str) -> str:
    return f"Candidate background:\n{resume_context}\n\nExtract and classify all skills."


# ---------------------------------------------------------------------------
# Required skills for target role
# ---------------------------------------------------------------------------

REQUIRED_SKILLS_SYSTEM_PROMPT = """\
You are a labor-market and industry-requirements expert. Given a target job
role, industry, and seniority level, determine the realistic current-day
skill requirements a hiring manager would expect. Separate:
- must_have_skills: non-negotiable core skills for this role today.
- good_to_have_skills: skills that strengthen a candidate but aren't required.
- typical_tools: concrete tools/platforms commonly used in this role.
Base this on realistic, current industry expectations, not an idealized list.
Keep lists focused (roughly 6-12 must-have skills) rather than exhaustive.
"""


def build_required_skills_user_prompt(
    role: str, industry: str, seniority_level: str
) -> str:
    return (
        f"Target role: {role}\n"
        f"Industry: {industry}\n"
        f"Seniority level: {seniority_level}\n\n"
        "Determine the required skills for this role."
    )


# ---------------------------------------------------------------------------
# Skill gap analysis
# ---------------------------------------------------------------------------

SKILL_GAP_SYSTEM_PROMPT = """\
You are a skills-gap analyst. Compare a candidate's current skills against
the skills required for their target role. Determine:
- matched_skills: required skills the candidate clearly already has.
- missing_skills: required skills the candidate does not have.
- partially_matched_skills: skills the candidate has some exposure to but
  likely not at the depth the role requires.
- skill_match_percentage: (matched / total required) * 100, rounded sensibly,
  where partially matched skills count as half a match.
Match skills semantically (e.g. "JS" matches "JavaScript"), not just by exact
string comparison.
"""


def build_skill_gap_user_prompt(
    current_skills: list[str], required_skills: list[str], good_to_have_skills: list[str]
) -> str:
    return (
        f"Candidate's current skills:\n{current_skills}\n\n"
        f"Role's must-have required skills:\n{required_skills}\n\n"
        f"Role's good-to-have skills:\n{good_to_have_skills}\n\n"
        "Perform the skill gap analysis."
    )


# ---------------------------------------------------------------------------
# Learning roadmap
# ---------------------------------------------------------------------------

ROADMAP_SYSTEM_PROMPT = """\
You are a learning-path designer for career changers and upskillers. Given a
candidate's missing skills and target role, build a realistic, motivating
30/60/90-day roadmap. Requirements:
- Each phase (30/60/90) must have concrete milestones and week-by-week goals.
- Early weeks should focus on foundational gaps; later weeks on integration
  and portfolio-building.
- Weekly goals must be specific and actionable (not vague like "learn Python").
- Do not repeat the same milestone across phases; each phase should build on
  the last.
"""


def build_roadmap_user_prompt(
    missing_skills: list[str], target_role: str, current_skills: list[str]
) -> str:
    return (
        f"Target role: {target_role}\n"
        f"Candidate's existing skills: {current_skills}\n"
        f"Missing skills to close: {missing_skills}\n\n"
        "Design the 30/60/90-day learning roadmap."
    )


# ---------------------------------------------------------------------------
# Course recommendations
# ---------------------------------------------------------------------------

COURSE_RECOMMENDATION_SYSTEM_PROMPT = """\
You are a learning-resources curator. Given a list of missing skills, recommend
real, well-known, currently-existing learning resources for each. Prefer
widely-recognized providers (Coursera, edX, Udemy, freeCodeCamp, official
documentation, YouTube channels known for quality tutorials, etc.). Only
include a URL if you are confident it is a real, canonical resource page;
otherwise leave the URL empty rather than inventing one. Provide a mix of
free_courses, paid_courses, certifications, books, and youtube_resources.
"""


def build_course_recommendation_user_prompt(missing_skills: list[str], target_role: str) -> str:
    return (
        f"Target role: {target_role}\n"
        f"Missing skills needing learning resources: {missing_skills}\n\n"
        "Recommend learning resources for these skills."
    )


# ---------------------------------------------------------------------------
# Project recommendations
# ---------------------------------------------------------------------------

PROJECT_RECOMMENDATION_SYSTEM_PROMPT = """\
You are a technical mentor designing portfolio projects. Given a candidate's
missing skills and target role, propose hands-on projects that would let them
practice and demonstrate those specific skills. Each project must specify a
title, difficulty, a concrete description (not generic), the skills it
teaches, and a realistic estimated time. Order projects from easiest to
hardest, and ensure collectively they cover most of the missing skills.
"""


def build_project_recommendation_user_prompt(
    missing_skills: list[str], target_role: str
) -> str:
    return (
        f"Target role: {target_role}\n"
        f"Missing skills to build projects around: {missing_skills}\n\n"
        "Propose 3-5 portfolio projects."
    )


# ---------------------------------------------------------------------------
# Resume review / ATS
# ---------------------------------------------------------------------------

RESUME_REVIEW_SYSTEM_PROMPT = """\
You are an ATS (Applicant Tracking System) and resume-review expert. Given a
candidate's raw resume text and their target role, evaluate:
- ats_score: 0-100 estimate of how well this resume would parse and rank in a
  typical ATS for this target role (consider formatting cues, keyword
  coverage, and section structure as far as can be inferred from plain text).
- weak_sections: which resume sections are missing, thin, or poorly structured.
- suggested_improvements: concrete, actionable rewrite suggestions.
- missing_keywords: important role-relevant keywords/skills absent from the
  resume that should be added (if truthfully applicable to the candidate).
Be honest and specific; avoid generic filler feedback.
"""


def build_resume_review_user_prompt(resume_text: str, target_role: str) -> str:
    return (
        f"Target role: {target_role}\n\n"
        f"Resume text:\n---\n{resume_text}\n---\n\n"
        "Review this resume."
    )


# ---------------------------------------------------------------------------
# Interview questions
# ---------------------------------------------------------------------------

INTERVIEW_QUESTIONS_SYSTEM_PROMPT = """\
You are a hiring manager preparing an interview loop for a specific role.
Generate realistic interview questions across four categories: hr_questions,
technical_questions, behavioral_questions, and role_specific_questions. Tailor
technical and role-specific questions precisely to the target role and the
candidate's skill gaps (favor questions that would probe both their strengths
and their weaker areas). Provide 4-6 questions per category.
"""


def build_interview_questions_user_prompt(
    target_role: str, matched_skills: list[str], missing_skills: list[str]
) -> str:
    return (
        f"Target role: {target_role}\n"
        f"Candidate's matched skills: {matched_skills}\n"
        f"Candidate's missing/weaker skills: {missing_skills}\n\n"
        "Generate the interview question set."
    )


# ---------------------------------------------------------------------------
# Career summary
# ---------------------------------------------------------------------------

CAREER_SUMMARY_SYSTEM_PROMPT = """\
You are a senior career coach producing the final report for a candidate after
a full analysis pipeline (resume parsing, skill-gap analysis, learning
roadmap, course/project recommendations, resume review, and interview prep).
Summarize everything into an encouraging but realistic final report:
- headline: one sentence capturing their career positioning.
- overview: a few paragraphs synthesizing the full picture.
- strengths: their clearest current strengths.
- priority_actions: the 3-5 highest-leverage next actions, ordered.
- confidence_score: your confidence (0-100) in the overall analysis, factoring
  in how complete the input data was.
"""


def build_career_summary_user_prompt(full_context: str) -> str:
    return f"Full analysis context:\n{full_context}\n\nWrite the final career summary report."

"""**LLM Call Wrapper with structured output+retries**"""

import json
import re
import time
from functools import lru_cache
from typing import TypeVar

from groq import Groq
from pydantic import BaseModel

SchemaT = TypeVar("SchemaT", bound=BaseModel)

_RETRY_AFTER_PATTERN = re.compile(
    r"try again in (?:(?P<minutes>\d+)m\s*)?(?P<seconds>[\d.]+)s", re.IGNORECASE
)

MIN_SECONDS_BETWEEN_CALLS = 15.0
_last_call_timestamp: float = 0.0


class LLMGenerationError(Exception):
    """Raised when an LLM call fails after all configured retries."""


@lru_cache
def _get_client() -> Groq:
    return Groq(api_key=os.environ["GROQ_API_KEY"])


def _extract_retry_after_seconds(exc: Exception) -> float | None:
    match = _RETRY_AFTER_PATTERN.search(str(exc))
    if not match:
        return None
    minutes = float(match.group("minutes") or 0)
    seconds = float(match.group("seconds") or 0)
    return minutes * 60 + seconds


def _is_rate_limit_error(exc: Exception) -> bool:
    text = str(exc).lower()
    return "429" in text or "rate_limit_exceeded" in text or "rate limit" in text


def _strip_markdown_fences(text: str) -> str:
    """Some models wrap JSON in ```json fences even in JSON mode; strip defensively."""
    text = text.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:]
    return text.strip()


def _pace_calls() -> None:
    global _last_call_timestamp
    elapsed = time.time() - _last_call_timestamp
    if elapsed < MIN_SECONDS_BETWEEN_CALLS:
        wait = MIN_SECONDS_BETWEEN_CALLS - elapsed
        print(f"[info] Pacing: waiting {wait:.1f}s before the next LLM call to stay under the TPM budget.")
        time.sleep(wait)
    _last_call_timestamp = time.time()


def get_structured_response(
    system_prompt: str,
    user_prompt: str,
    schema: type[SchemaT],
    max_tokens: int = 2000,
) -> SchemaT:
    """
    Call Groq directly (no LangChain) using native JSON mode, and validate the
    response into `schema`.

    Args:
        max_tokens: cap on completion length. Increase this for schemas with
            large expected output (e.g. LearningRoadmap) to avoid truncated,
            unparseable JSON.
    """
    client = _get_client()
    schema_json = json.dumps(schema.model_json_schema())

    full_system_prompt = (
        f"{system_prompt}\n\n"
        "Respond with ONLY a single valid JSON object — no markdown fences, "
        "no commentary, no explanation before or after — that strictly matches "
        f"this JSON schema:\n{schema_json}"
    )

    last_error: Exception | None = None
    attempts = LLM_MAX_RETRIES + 1

    for attempt in range(1, attempts + 1):
        _pace_calls()
        try:
            completion = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[
                    {"role": "system", "content": full_system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=LLM_TEMPERATURE,
                max_tokens=max_tokens,
                response_format={"type": "json_object"},
            )
            raw_text = completion.choices[0].message.content
            parsed = json.loads(_strip_markdown_fences(raw_text))
            return schema.model_validate(parsed)

        except Exception as exc:  # noqa: BLE001
            last_error = exc

            if attempt == attempts:
                print(f"[error] LLM call failed permanently for {schema.__name__}: {exc}")
                break

            if _is_rate_limit_error(exc):
                wait_seconds = _extract_retry_after_seconds(exc)
                if wait_seconds is None:
                    wait_seconds = 2.0 * attempt
                wait_seconds = min(wait_seconds + 1.0, 60.0)
                print(
                    f"[warn] Rate limited on {schema.__name__} "
                    f"(attempt {attempt}/{attempts}); waiting {wait_seconds:.1f}s before retrying."
                )
                time.sleep(wait_seconds)
            else:
                print(f"[warn] LLM call failed (attempt {attempt}/{attempts}) for {schema.__name__}: {exc}")
                time.sleep(1.5 * attempt)

    raise LLMGenerationError(
        f"Failed to get a valid '{schema.__name__}' response from the LLM after {attempts} attempt(s)."
    ) from last_error

"""**Strongly typed carrerstate**"""

from __future__ import annotations

from typing import Any, Optional, TypedDict


class CareerState(TypedDict, total=False):
    """Strongly typed shared state threaded through the entire graph."""

    # --- Raw inputs -------------------------------------------------------
    resume_file_bytes: bytes  # raw uploaded PDF bytes, consumed by the parser node
    resume_text: str
    stated_career_goal: str  # raw user input, e.g. "I want to become a data scientist"

    # --- Node 1-2: Resume parsing & extraction -----------------------------
    resume_extraction: Optional[ResumeExtraction]
    education: list[dict[str, Any]]
    experience: list[dict[str, Any]]
    projects: list[dict[str, Any]]
    certifications: list[dict[str, Any]]

    # --- Node 3: Career goal understanding ---------------------------------
    career_goal: Optional[CareerGoal]
    industry: str

    # --- Node 4: Current skill extraction -----------------------------------
    skill_extraction: Optional[SkillExtraction]
    current_skills: list[str]

    # --- Node 5: Required skills for target role ---------------------------
    required_skills_data: Optional[RequiredSkills]
    required_skills: list[str]

    # --- Node 6: Skill gap analysis ------------------------------------------
    skill_gap: Optional[SkillGapAnalysis]
    matched_skills: list[str]
    missing_skills: list[str]
    skill_match_percentage: float

    # --- Node 7: Learning roadmap ---------------------------------------------
    learning_path: Optional[LearningRoadmap]

    # --- Node 8: Course recommendations ----------------------------------------
    courses: Optional[CourseRecommendationSet]

    # --- Node 9: Project recommendations -----------------------------------------
    recommended_projects: Optional[ProjectRecommendationSet]

    # --- Node 10: Resume ATS review -----------------------------------------------
    resume_feedback: Optional[ResumeReview]
    ats_score: float

    # --- Node 11: Interview questions ----------------------------------------------
    interview_questions: Optional[InterviewQuestionSet]

    # --- Node 12: Career summary -----------------------------------------------------
    career_summary: Optional[CareerSummary]
    confidence_score: float

    # --- Cross-cutting concerns ----------------------------------------------------------
    errors: list[str]
    failed_nodes: list[str]

"""**Shared error handling helper**"""

from typing import Any


class _StubLogger:
    """Minimal print-based stand-in for the backend's real logger (utils/logger.py)."""

    def info(self, msg, *args):
        print("[info]", msg % args if args else msg)

    def warning(self, msg, *args):
        print("[warn]", msg % args if args else msg)

    def error(self, msg, *args):
        print("[error]", msg % args if args else msg)


def get_logger(name: str) -> _StubLogger:
    return _StubLogger()


logger = get_logger(__name__)


def with_node_error_handling(node_name: str, state: "CareerState", exc: Exception) -> dict[str, Any]:
    """Build a partial-state update recording a node failure, without raising."""
    logger.error("Node '%s' failed: %s", node_name, exc)
    existing_errors = list(state.get("errors", []))
    existing_failed = list(state.get("failed_nodes", []))
    existing_errors.append(f"{node_name}: {exc}")
    existing_failed.append(node_name)
    return {"errors": existing_errors, "failed_nodes": existing_failed}

"""**PDF Parsing helper**"""

import fitz  # PyMuPDF


class PDFExtractionError(Exception):
    """Raised when a PDF file cannot be opened or contains no extractable text."""


def extract_text_from_pdf_bytes(file_bytes: bytes) -> str:
    if not file_bytes:
        raise PDFExtractionError("Uploaded resume file is empty.")
    try:
        document = fitz.open(stream=file_bytes, filetype="pdf")
    except Exception as exc:
        raise PDFExtractionError("The uploaded file could not be read as a valid PDF.") from exc

    pages_text = []
    try:
        for page_index in range(document.page_count):
            pages_text.append(document.load_page(page_index).get_text("text"))
    finally:
        document.close()

    full_text = "\n".join(pages_text).strip()
    if not full_text:
        raise PDFExtractionError("No extractable text was found in the resume.")
    return full_text

from google.colab import files

print("Choose a resume PDF to upload...")
uploaded = files.upload()  # opens a file picker in the Colab UI

if not uploaded:
    raise ValueError("No file was uploaded.")

# Take the first uploaded file, whatever it's named
uploaded_filename = list(uploaded.keys())[0]
pdf_bytes = uploaded[uploaded_filename]

print(f"Uploaded '{uploaded_filename}' ({len(pdf_bytes)} bytes). Extracting text...")

resume_text_from_pdf = extract_text_from_pdf_bytes(pdf_bytes)

print(f"Extracted {len(resume_text_from_pdf)} characters.\n")
print("--- Preview (first 500 chars) ---")
print(resume_text_from_pdf[:500])

"""**Node 1: Resume_parser**"""

NODE_NAME_RESUME_PARSER = "resume_parser"


def resume_parser_node(state: CareerState) -> dict:
    """Extract raw text from the uploaded resume PDF bytes."""
    try:
        file_bytes = state.get("resume_file_bytes")
        existing_text = state.get("resume_text", "").strip() if state.get("resume_text") else ""

        # Allow callers to pass already-extracted text (e.g. from a non-PDF
        # source) and skip PDF parsing entirely.
        if existing_text:
            logger.info("resume_text already present in state; skipping PDF extraction.")
            return {"resume_text": existing_text}

        if not file_bytes:
            raise PDFExtractionError("No resume file bytes or resume text were provided.")

        raw_text = extract_text_from_pdf_bytes(file_bytes)
        return {"resume_text": raw_text}

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_RESUME_PARSER, state, exc)
        update["resume_text"] = state.get("resume_text", "")
        return update

"""**Node 2:extract_info**"""

NODE_NAME_EXTRACT_INFO = "extract_info"


def extract_info_node(state: CareerState) -> dict:
    """Extract structured education/experience/projects/certifications from resume text."""
    try:
        resume_text = state.get("resume_text", "").strip()
        if not resume_text:
            raise ValueError("Cannot extract resume information: resume_text is empty.")

        extraction: ResumeExtraction = get_structured_response(
            system_prompt=RESUME_EXTRACTION_SYSTEM_PROMPT,
            user_prompt=build_resume_extraction_user_prompt(resume_text),
            schema=ResumeExtraction,
        )

        return {
            "resume_extraction": extraction,
            "education": [entry.model_dump() for entry in extraction.education],
            "experience": [entry.model_dump() for entry in extraction.experience],
            "projects": [entry.model_dump() for entry in extraction.projects],
            "certifications": [entry.model_dump() for entry in extraction.certifications],
        }

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_EXTRACT_INFO, state, exc)
        update.setdefault("education", state.get("education", []))
        update.setdefault("experience", state.get("experience", []))
        update.setdefault("projects", state.get("projects", []))
        update.setdefault("certifications", state.get("certifications", []))
        return update

"""**Node 3:career_goal**"""

NODE_NAME_CAREER_GOAL = "career_goal"


def _build_resume_summary_context(state: CareerState) -> str:
    experience = state.get("experience", [])
    education = state.get("education", [])
    parts = []
    if experience:
        latest = experience[0]
        parts.append(f"Most recent role: {latest.get('role', 'N/A')} at {latest.get('company', 'N/A')}")
    if education:
        parts.append(f"Highest/most recent education: {education[0].get('degree', 'N/A')}")
    return "\n".join(parts) if parts else "No resume context available."


def career_goal_node(state: CareerState) -> dict:
    """Determine the candidate's structured career goal."""
    try:
        stated_goal = state.get("stated_career_goal", "").strip()
        if not stated_goal:
            raise ValueError("Missing required input: stated_career_goal was not provided.")

        goal: CareerGoal = get_structured_response(
            system_prompt=CAREER_GOAL_SYSTEM_PROMPT,
            user_prompt=build_career_goal_user_prompt(
                stated_goal=stated_goal,
                resume_summary_context=_build_resume_summary_context(state),
            ),
            schema=CareerGoal,
        )

        return {"career_goal": goal, "industry": goal.desired_industry}

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_CAREER_GOAL, state, exc)
        update.setdefault("industry", state.get("industry", ""))
        return update

"""**Node 4: skill_extractor**"""

NODE_NAME_SKILL_EXTRACTOR = "skill_extractor"


def _build_resume_context(state: CareerState) -> str:
    return (
        f"Resume text:\n{state.get('resume_text', '')}\n\n"
        f"Experience: {state.get('experience', [])}\n"
        f"Projects: {state.get('projects', [])}\n"
        f"Certifications: {state.get('certifications', [])}"
    )


def skill_extractor_node(state: CareerState) -> dict:
    """Extract and classify the candidate's current skills."""
    try:
        resume_text = state.get("resume_text", "").strip()
        if not resume_text:
            raise ValueError("Cannot extract skills: resume_text is empty.")

        extraction: SkillExtraction = get_structured_response(
            system_prompt=SKILL_EXTRACTION_SYSTEM_PROMPT,
            user_prompt=build_skill_extraction_user_prompt(_build_resume_context(state)),
            schema=SkillExtraction,
        )

        all_skills = list(
            dict.fromkeys(  # de-duplicate while preserving order
                extraction.technical_skills
                + extraction.soft_skills
                + extraction.tools_and_platforms
            )
        )

        return {"skill_extraction": extraction, "current_skills": all_skills}

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_SKILL_EXTRACTOR, state, exc)
        update.setdefault("current_skills", state.get("current_skills", []))
        return update

"""**Node 5: required_skills**"""

NODE_NAME_REQUIRED_SKILLS = "required_skills"


def required_skills_node(state: CareerState) -> dict:
    """Determine required skills for the candidate's target role."""
    try:
        career_goal = state.get("career_goal")
        if career_goal is None:
            raise ValueError("Cannot determine required skills: career_goal was not resolved.")

        required: RequiredSkills = get_structured_response(
            system_prompt=REQUIRED_SKILLS_SYSTEM_PROMPT,
            user_prompt=build_required_skills_user_prompt(
                role=career_goal.desired_role,
                industry=career_goal.desired_industry,
                seniority_level=career_goal.seniority_level,
            ),
            schema=RequiredSkills,
        )

        combined = list(
            dict.fromkeys(required.must_have_skills + required.good_to_have_skills)
        )

        return {"required_skills_data": required, "required_skills": combined}

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_REQUIRED_SKILLS, state, exc)
        update.setdefault("required_skills", state.get("required_skills", []))
        return update

"""**Node 6:skill_gap**"""

NODE_NAME_SKILL_GAP = "skill_gap"


def skill_gap_node(state: CareerState) -> dict:
    """Compare current vs. required skills to compute the skill gap."""
    try:
        current_skills = state.get("current_skills", [])
        required_skills = state.get("required_skills", [])
        required_data = state.get("required_skills_data")

        if not required_skills:
            raise ValueError("Cannot compute skill gap: no required skills were resolved.")

        good_to_have = required_data.good_to_have_skills if required_data else []
        must_have = required_data.must_have_skills if required_data else required_skills

        gap: SkillGapAnalysis = get_structured_response(
            system_prompt=SKILL_GAP_SYSTEM_PROMPT,
            user_prompt=build_skill_gap_user_prompt(
                current_skills=current_skills,
                required_skills=must_have,
                good_to_have_skills=good_to_have,
            ),
            schema=SkillGapAnalysis,
        )

        return {
            "skill_gap": gap,
            "matched_skills": gap.matched_skills,
            "missing_skills": gap.missing_skills,
            "skill_match_percentage": gap.skill_match_percentage,
        }

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_SKILL_GAP, state, exc)
        update.setdefault("matched_skills", state.get("matched_skills", []))
        update.setdefault("missing_skills", state.get("missing_skills", []))
        update.setdefault("skill_match_percentage", state.get("skill_match_percentage", 0.0))
        return update

"""**Node 7: roadmap**"""

NODE_NAME_ROADMAP = "roadmap"


def roadmap_node(state: CareerState) -> dict:
    """Generate the 30/60/90-day learning roadmap."""
    try:
        missing_skills = state.get("missing_skills", [])
        career_goal = state.get("career_goal")
        target_role = career_goal.desired_role if career_goal else "the target role"

        roadmap: LearningRoadmap = get_structured_response(
            system_prompt=ROADMAP_SYSTEM_PROMPT,
            user_prompt=build_roadmap_user_prompt(
                missing_skills=missing_skills or ["deepen existing expertise"],
                target_role=target_role,
                current_skills=state.get("current_skills", []),
            ),
            schema=LearningRoadmap,
            max_tokens=3500,  # this schema is the largest; avoid truncated JSON
        )

        return {"learning_path": roadmap}

    except Exception as exc:  # noqa: BLE001
        return with_node_error_handling(NODE_NAME_ROADMAP, state, exc)

"""**Node 8:courses**"""

NODE_NAME_COURSES = "courses"


def courses_node(state: CareerState) -> dict:
    """Recommend learning resources for the candidate's missing skills."""
    try:
        missing_skills = state.get("missing_skills", [])
        career_goal = state.get("career_goal")
        target_role = career_goal.desired_role if career_goal else "the target role"

        if not missing_skills:
            raise ValueError("No missing skills available to base course recommendations on.")

        courses: CourseRecommendationSet = get_structured_response(
            system_prompt=COURSE_RECOMMENDATION_SYSTEM_PROMPT,
            user_prompt=build_course_recommendation_user_prompt(
                missing_skills=missing_skills, target_role=target_role
            ),
            schema=CourseRecommendationSet,
        )

        return {"courses": courses}

    except Exception as exc:  # noqa: BLE001
        return with_node_error_handling(NODE_NAME_COURSES, state, exc)

"""**Node 9: projects**"""

NODE_NAME_PROJECTS = "projects"


def projects_node(state: CareerState) -> dict:
    """Generate project ideas based on the candidate's missing skills."""
    try:
        missing_skills = state.get("missing_skills", [])
        career_goal = state.get("career_goal")
        target_role = career_goal.desired_role if career_goal else "the target role"

        if not missing_skills:
            raise ValueError("No missing skills available to base project recommendations on.")

        project_set: ProjectRecommendationSet = get_structured_response(
            system_prompt=PROJECT_RECOMMENDATION_SYSTEM_PROMPT,
            user_prompt=build_project_recommendation_user_prompt(
                missing_skills=missing_skills, target_role=target_role
            ),
            schema=ProjectRecommendationSet,
        )

        return {"recommended_projects": project_set}

    except Exception as exc:  # noqa: BLE001
        return with_node_error_handling(NODE_NAME_PROJECTS, state, exc)

"""**Node 10: resume_review**"""

NODE_NAME_RESUME_REVIEW = "resume_review"


def resume_review_node(state: CareerState) -> dict:
    """Review the resume and produce an ATS score with actionable feedback."""
    try:
        resume_text = state.get("resume_text", "").strip()
        career_goal = state.get("career_goal")
        target_role = career_goal.desired_role if career_goal else "the target role"

        if not resume_text:
            raise ValueError("Cannot review resume: resume_text is empty.")

        review: ResumeReview = get_structured_response(
            system_prompt=RESUME_REVIEW_SYSTEM_PROMPT,
            user_prompt=build_resume_review_user_prompt(
                resume_text=resume_text, target_role=target_role
            ),
            schema=ResumeReview,
        )

        return {"resume_feedback": review, "ats_score": review.ats_score}

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_RESUME_REVIEW, state, exc)
        update.setdefault("ats_score", state.get("ats_score", 0.0))
        return update

"""**Node 11:interview**"""

NODE_NAME_INTERVIEW = "interview"


def interview_node(state: CareerState) -> dict:
    """Generate a tailored interview question set."""
    try:
        career_goal = state.get("career_goal")
        target_role = career_goal.desired_role if career_goal else "the target role"

        questions: InterviewQuestionSet = get_structured_response(
            system_prompt=INTERVIEW_QUESTIONS_SYSTEM_PROMPT,
            user_prompt=build_interview_questions_user_prompt(
                target_role=target_role,
                matched_skills=state.get("matched_skills", []),
                missing_skills=state.get("missing_skills", []),
            ),
            schema=InterviewQuestionSet,
        )

        return {"interview_questions": questions}

    except Exception as exc:  # noqa: BLE001
        return with_node_error_handling(NODE_NAME_INTERVIEW, state, exc)

"""**Node 12: summary**"""

NODE_NAME_SUMMARY = "summary"


def _build_full_context(state: CareerState) -> str:
    career_goal = state.get("career_goal")
    return (
        f"Career goal: {career_goal.model_dump() if career_goal else 'unresolved'}\n"
        f"Current skills: {state.get('current_skills', [])}\n"
        f"Matched skills: {state.get('matched_skills', [])}\n"
        f"Missing skills: {state.get('missing_skills', [])}\n"
        f"Skill match percentage: {state.get('skill_match_percentage', 0.0)}\n"
        f"ATS score: {state.get('ats_score', 0.0)}\n"
        f"Number of nodes that failed: {len(state.get('failed_nodes', []))}\n"
        f"Failed nodes: {state.get('failed_nodes', [])}\n"
    )


def summary_node(state: CareerState) -> dict:
    """Produce the final career summary report and overall confidence score."""
    try:
        summary: CareerSummary = get_structured_response(
            system_prompt=CAREER_SUMMARY_SYSTEM_PROMPT,
            user_prompt=build_career_summary_user_prompt(_build_full_context(state)),
            schema=CareerSummary,
        )

        # Deduct confidence proportionally to how many nodes failed upstream,
        # so a report built on partial data is never reported as fully confident.
        failed_count = len(state.get("failed_nodes", []))
        adjusted_confidence = max(0.0, summary.confidence_score - (failed_count * 10))

        return {"career_summary": summary, "confidence_score": adjusted_confidence}

    except Exception as exc:  # noqa: BLE001
        update = with_node_error_handling(NODE_NAME_SUMMARY, state, exc)
        update.setdefault("confidence_score", 0.0)
        return update

"""**Abort Node (deterministic early exit for unusable resumes)**"""

def abort_node(state: CareerState) -> dict:
    """Build a minimal, explanatory result when the pipeline cannot proceed. No LLM call needed."""
    errors = state.get("errors", [])
    reason = errors[-1] if errors else "The resume could not be processed."

    logger.info("Pipeline aborted early. Reason: %s", reason)

    summary = CareerSummary(
        headline="We couldn't complete your career analysis.",
        overview=(
            "The pipeline stopped early because we could not extract usable "
            "content from the uploaded resume. Please re-upload a text-based "
            f"PDF resume and try again. Details: {reason}"
        ),
        strengths=[],
        priority_actions=[
            "Re-upload a text-based (non-scanned) PDF resume.",
            "Ensure the file is not corrupted or password-protected.",
        ],
        confidence_score=0.0,
    )

    return {"career_summary": summary, "confidence_score": 0.0}

"""**Conditional edge routing logic**"""

from typing import Literal


def route_after_resume_parsing(state: CareerState) -> Literal["continue", "abort"]:
    """If no usable resume text exists, short-circuit straight to the abort node."""
    resume_text = state.get("resume_text", "").strip()
    if not resume_text:
        logger.warning("Routing to 'abort': no resume text available after parsing.")
        return "abort"
    return "continue"


def route_after_career_goal(state: CareerState) -> Literal["continue", "degraded"]:
    """If the career goal couldn't be resolved, route to the degraded (role-agnostic) path."""
    if state.get("career_goal") is None:
        logger.warning("Routing to 'degraded': career_goal could not be resolved.")
        return "degraded"
    return "continue"

"""**wire everything into a compiled stateGraph**"""

from langgraph.graph import END, START, StateGraph


def build_career_advisor_graph(checkpointer=None):
    """
    Construct and compile the Career Advisor StateGraph.

    Pass a `checkpointer` (e.g. `langgraph.checkpoint.memory.MemorySaver`) to
    add multi-turn memory. Use `compile(interrupt_before=[...])` to add a
    human-in-the-loop pause before any node.
    """
    graph = StateGraph(CareerState)

    graph.add_node("resume_parser", resume_parser_node)
    graph.add_node("abort", abort_node)
    graph.add_node("extract_info", extract_info_node)
    graph.add_node("career_goal_node", career_goal_node)
    graph.add_node("skill_extractor", skill_extractor_node)
    graph.add_node("required_skills_node", required_skills_node)
    graph.add_node("skill_gap_node", skill_gap_node)
    graph.add_node("roadmap", roadmap_node)
    graph.add_node("courses_node", courses_node)
    graph.add_node("projects_node", projects_node)
    graph.add_node("resume_review", resume_review_node)
    graph.add_node("interview", interview_node)
    graph.add_node("summary", summary_node)

    graph.add_edge(START, "resume_parser")

    graph.add_conditional_edges(
        "resume_parser",
        route_after_resume_parsing,
        {"continue": "extract_info", "abort": "abort"},
    )
    graph.add_edge("abort", END)

    graph.add_edge("extract_info", "career_goal_node")

    graph.add_conditional_edges(
        "career_goal_node",
        route_after_career_goal,
        {"continue": "skill_extractor", "degraded": "skill_extractor"},
    )

    graph.add_conditional_edges(
        "skill_extractor",
        lambda state: "continue" if state.get("career_goal") is not None else "degraded",
        {"continue": "required_skills_node", "degraded": "resume_review"},
    )

    graph.add_edge("required_skills_node", "skill_gap_node")
    graph.add_edge("skill_gap_node", "roadmap")
    graph.add_edge("roadmap", "courses_node")
    graph.add_edge("courses_node", "projects_node")
    graph.add_edge("projects_node", "resume_review")

    graph.add_edge("resume_review", "interview")
    graph.add_edge("interview", "summary")
    graph.add_edge("summary", END)

    return graph.compile(checkpointer=checkpointer)


career_advisor_graph = build_career_advisor_graph()
import time
_original_invoke = career_advisor_graph.invoke

def _throttled_invoke(*args, **kwargs):
    # not needed usually — the backoff above handles bursts already.
    return _original_invoke(*args, **kwargs)
print("Graph compiled. Nodes:", list(career_advisor_graph.get_graph().nodes.keys()))

# !pip install -q grandalf

from IPython.display import Image, display

try:
    display(Image(career_advisor_graph.get_graph().draw_mermaid_png()))
except Exception as e:
    print("Mermaid image rendering needs outbound internet to mermaid.ink — falling back to ASCII.\n")
    print(career_advisor_graph.get_graph().draw_ascii())
    print("\n(You can also paste this into https://mermaid.live to view it as a diagram:)\n")
    print(career_advisor_graph.get_graph().draw_mermaid())

"""**test run**"""

career_goal_input = input("What's your career goal? (e.g. 'Data Scientist in fintech'): ")

initial_state = {
    "resume_text": resume_text_from_pdf,   # from the upload cell above
    "stated_career_goal": career_goal_input,
    "errors": [],
    "failed_nodes": [],
}

final_state = career_advisor_graph.invoke(initial_state)

print("\nCareer goal:", final_state.get("career_goal"))
print("Skill match %:", final_state.get("skill_match_percentage"))
print("Missing skills:", final_state.get("missing_skills"))
print("Career summary:", final_state.get("career_summary").headline if final_state.get("career_summary") else None)
print("Errors:", final_state.get("errors"))